/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/coroutine-and-data-structure/': RouteRecordInfo<'/posts/coroutine-and-data-structure/', '/posts/coroutine-and-data-structure', Record<never, never>, Record<never, never>>,
    '/posts/cross-language-call/': RouteRecordInfo<'/posts/cross-language-call/', '/posts/cross-language-call', Record<never, never>, Record<never, never>>,
    '/posts/csharp-advanced/': RouteRecordInfo<'/posts/csharp-advanced/', '/posts/csharp-advanced', Record<never, never>, Record<never, never>>,
    '/posts/csharp-ref-modifiers/': RouteRecordInfo<'/posts/csharp-ref-modifiers/', '/posts/csharp-ref-modifiers', Record<never, never>, Record<never, never>>,
    '/posts/design-pattern-object-pool-ecs/': RouteRecordInfo<'/posts/design-pattern-object-pool-ecs/', '/posts/design-pattern-object-pool-ecs', Record<never, never>, Record<never, never>>,
    '/posts/lua-depth': RouteRecordInfo<'/posts/lua-depth', '/posts/lua-depth', Record<never, never>, Record<never, never>>,
    '/posts/raycast': RouteRecordInfo<'/posts/raycast', '/posts/raycast', Record<never, never>, Record<never, never>>,
    '/posts/transform-forward-vs-vector3-forward': RouteRecordInfo<'/posts/transform-forward-vs-vector3-forward', '/posts/transform-forward-vs-vector3-forward', Record<never, never>, Record<never, never>>,
    '/posts/unitask': RouteRecordInfo<'/posts/unitask', '/posts/unitask', Record<never, never>, Record<never, never>>,
    '/posts/unity-coroutine-principle': RouteRecordInfo<'/posts/unity-coroutine-principle', '/posts/unity-coroutine-principle', Record<never, never>, Record<never, never>>,
    '/posts/unity-editor-crash-debug': RouteRecordInfo<'/posts/unity-editor-crash-debug', '/posts/unity-editor-crash-debug', Record<never, never>, Record<never, never>>,
    '/posts/unity-ml-agents-study/': RouteRecordInfo<'/posts/unity-ml-agents-study/', '/posts/unity-ml-agents-study', Record<never, never>, Record<never, never>>,
    '/posts/unity-particle-system-1': RouteRecordInfo<'/posts/unity-particle-system-1', '/posts/unity-particle-system-1', Record<never, never>, Record<never, never>>,
    '/posts/unity-particle-system-2': RouteRecordInfo<'/posts/unity-particle-system-2', '/posts/unity-particle-system-2', Record<never, never>, Record<never, never>>,
    '/posts/unity-shader-rendering-1/': RouteRecordInfo<'/posts/unity-shader-rendering-1/', '/posts/unity-shader-rendering-1', Record<never, never>, Record<never, never>>,
    '/posts/unity-shader-rendering-2/': RouteRecordInfo<'/posts/unity-shader-rendering-2/', '/posts/unity-shader-rendering-2', Record<never, never>, Record<never, never>>,
    '/posts/unity-shader-rendering-3/': RouteRecordInfo<'/posts/unity-shader-rendering-3/', '/posts/unity-shader-rendering-3', Record<never, never>, Record<never, never>>,
    '/posts/unity-shader-rendering-4/': RouteRecordInfo<'/posts/unity-shader-rendering-4/', '/posts/unity-shader-rendering-4', Record<never, never>, Record<never, never>>,
    '/posts/xlua-hotfix': RouteRecordInfo<'/posts/xlua-hotfix', '/posts/xlua-hotfix', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__78e6711f426cc07bcc0cd11caa060053/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.6_@babel+parser_dcad8b5bef2adef0d1120706fc8a36b7/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__78e6711f426cc07bcc0cd11caa060053/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'pages/posts/coroutine-and-data-structure/index.md': {
      routes: '/posts/coroutine-and-data-structure/'
      views: never
    }
    'pages/posts/cross-language-call/index.md': {
      routes: '/posts/cross-language-call/'
      views: never
    }
    'pages/posts/csharp-advanced/index.md': {
      routes: '/posts/csharp-advanced/'
      views: never
    }
    'pages/posts/csharp-ref-modifiers/index.md': {
      routes: '/posts/csharp-ref-modifiers/'
      views: never
    }
    'pages/posts/design-pattern-object-pool-ecs/index.md': {
      routes: '/posts/design-pattern-object-pool-ecs/'
      views: never
    }
    'pages/posts/lua-depth.md': {
      routes: '/posts/lua-depth'
      views: never
    }
    'pages/posts/raycast.md': {
      routes: '/posts/raycast'
      views: never
    }
    'pages/posts/transform-forward-vs-vector3-forward.md': {
      routes: '/posts/transform-forward-vs-vector3-forward'
      views: never
    }
    'pages/posts/unitask.md': {
      routes: '/posts/unitask'
      views: never
    }
    'pages/posts/unity-coroutine-principle.md': {
      routes: '/posts/unity-coroutine-principle'
      views: never
    }
    'pages/posts/unity-editor-crash-debug.md': {
      routes: '/posts/unity-editor-crash-debug'
      views: never
    }
    'pages/posts/unity-ml-agents-study/index.md': {
      routes: '/posts/unity-ml-agents-study/'
      views: never
    }
    'pages/posts/unity-particle-system-1.md': {
      routes: '/posts/unity-particle-system-1'
      views: never
    }
    'pages/posts/unity-particle-system-2.md': {
      routes: '/posts/unity-particle-system-2'
      views: never
    }
    'pages/posts/unity-shader-rendering-1/index.md': {
      routes: '/posts/unity-shader-rendering-1/'
      views: never
    }
    'pages/posts/unity-shader-rendering-2/index.md': {
      routes: '/posts/unity-shader-rendering-2/'
      views: never
    }
    'pages/posts/unity-shader-rendering-3/index.md': {
      routes: '/posts/unity-shader-rendering-3/'
      views: never
    }
    'pages/posts/unity-shader-rendering-4/index.md': {
      routes: '/posts/unity-shader-rendering-4/'
      views: never
    }
    'pages/posts/xlua-hotfix.md': {
      routes: '/posts/xlua-hotfix'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
